language: php

php:
  #- 5.4
  #- 5.5
  - 5.6

services:
  - mysql
  - memcached

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - APPLICATION_ENV="travis"
  matrix:
    - PHALCON_VERSION="2.0.8"
    - PHALCON_VERSION="2.0.7"
    - PHALCON_VERSION="2.0.6"
    - PHALCON_VERSION="2.0.5"

install:
  - composer self-update
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b phalcon-v${PHALCON_VERSION}
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j4 > /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini &> /dev/null)
  - php -r 'echo \Phalcon\Version::get() . PHP_EOL;'
  - composer install --prefer-source --no-interaction

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password__phanbook') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - cp ./core/config/config.example.php ./core/config/config.php
  - cp ./tests/config.travis.php ./core/config/config.travis.php
  - mysql -e 'CREATE DATABASE phanbook CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;' -uroot -ppassword__phanbook
  - cat schema/phanbook.sql | mysql -uroot phanbook -ppassword__phanbook
  #- (cd ./scripts/ && php random-entries.php > /dev/null)
  - php -S 127.0.0.1:8000 -t . .htrouter.php >/dev/null 2>&1 &

after_script:
  #- mysql -e 'DROP DATABASE phanbook;' -uroot -ppassword__phanbook

script:
  - vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 --ignore=core/common/library/Markdown  core/
  - vendor/bin/codecept build
  - vendor/bin/codecept run

notifications:
  email:
    - hello@phanbook.com
  slack: phanbook:V3Gun19jnfnRafcTbvn5mFuY
addons:
  hosts:
    - db
    - phanbook.dev

